<a href="https://colab.research.google.com/github/farazrahman/CaseStudy_grades/blob/master/Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [6]:
#Description
#Create a 3*3 array using list_1 = [1,2,3] list_2 = [4,5,6] list_3 = [7,8,9]

list_1 = [1,2,3]
list_2 = [4,5,6] 
list_3 = [7,8,9]

array_3d = np.array([[list_1], [list_2], [list_3]])

print(array_3d)

print(type(array_3d))

[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]
<class 'numpy.ndarray'>


In [14]:
#Description
#Perform an element-wise multiplication using list_1 = [2,3,4,5] list_2 = [7,8,9,6] and obtain the output as a list. 

list_1 = [2,3,4,5] 
list_2 = [7,8,9,6]

list_1 = np.array(list_1)
list_2 = np.array(list_2)

array_product = list_1*list_2

print(array_product)

print(type(array_product))

#Convert the product array to list

array_list = list(array_product)

print(type(array_list))

[14 24 36 30]
<class 'numpy.ndarray'>
<class 'list'>


In [19]:
#Description
#Convert a list list_1 = [1,2,3,4] and a tuple tuple_1 = (5,6,7,8) to an array.

list_1 = [1,2,3,4] 
tuple_1 = (5,6,7,8)

list_array = np.array(list_1)
tupple_array = np.array(tuple_1)

print(list_array)
print(tupple_array)

print(type(list_array))
print(type(tupple_array))

[1 2 3 4]
[5 6 7 8]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [22]:
#Description
#Create an array of all ones of size 3*3 having integer values. 
#Hint: Use dtype to specify integer.

array_ones = np.ones((3,3), dtype = int)

print(type(array_ones))

print(array_ones)

<class 'numpy.ndarray'>
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [26]:
#Description
#Create an array of first 10 multiples of 5 using the 'arange' function.

array_multiplesof5 = np.arange(5,55,5)

print(array_multiplesof5)



[ 5 10 15 20 25 30 35 40 45 50]
